# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Modu < Formula
  desc "多模块 Git Worktree 管理工具"
  homepage "https://github.com/qimao/modu"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/qimaotech/modu/releases/download/v0.5.0/modu_0.5.0_darwin_amd64.tar.gz"
      sha256 "7618eb72158d40d2b905e8c7d0298bd5bd3601ff07339efdf54fb706cf08d809"

      define_method(:install) do
        bin.install "modu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/qimaotech/modu/releases/download/v0.5.0/modu_0.5.0_darwin_arm64.tar.gz"
      sha256 "df2c713ae61ecb3d791492665d7026bda3d46251de4f95923175252ea7e3cc6e"

      define_method(:install) do
        bin.install "modu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/qimaotech/modu/releases/download/v0.5.0/modu_0.5.0_linux_amd64.tar.gz"
      sha256 "b805c2e41f98d05c57e907e218e04b1692ac9a4a557e1414e1a4d15e8825a11f"
      define_method(:install) do
        bin.install "modu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qimaotech/modu/releases/download/v0.5.0/modu_0.5.0_linux_arm64.tar.gz"
      sha256 "69eb8d4c49afa7266eea3bfddd7997f225f09852f12abe2fbbb53c4becf86f09"
      define_method(:install) do
        bin.install "modu"
      end
    end
  end
end
