# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Modu < Formula
  desc "多模块 Git Worktree 管理工具"
  homepage "https://github.com/qimao/modu"
  version "0.6.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/qimaotech/modu/releases/download/v0.6.8/modu_0.6.8_darwin_amd64.tar.gz"
      sha256 "9e19d9d9ae3cb0da09b112307f55e0f65ca3ff57075a1c0a133d7e95e3547d4e"

      define_method(:install) do
        bin.install "modu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/qimaotech/modu/releases/download/v0.6.8/modu_0.6.8_darwin_arm64.tar.gz"
      sha256 "d7c0b024a52c788f151ac599137a2e27e30cd050d9669cc6ba2f899733f57bc2"

      define_method(:install) do
        bin.install "modu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/qimaotech/modu/releases/download/v0.6.8/modu_0.6.8_linux_amd64.tar.gz"
      sha256 "ca4d12804a0a2e43883d23f7a3668b5ada604ed2805d8465e27aa7a3006f7ada"
      define_method(:install) do
        bin.install "modu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qimaotech/modu/releases/download/v0.6.8/modu_0.6.8_linux_arm64.tar.gz"
      sha256 "7af0e0c5362b08c0d88bbecbaa46fcaa5597d687b9e6d514f4b24f76193fd0aa"
      define_method(:install) do
        bin.install "modu"
      end
    end
  end
end
