# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Modu < Formula
  desc "多模块 Git Worktree 管理工具"
  homepage "https://github.com/qimao/modu"
  version "0.6.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/qimaotech/modu/releases/download/v0.6.5/modu_0.6.5_darwin_amd64.tar.gz"
      sha256 "940daac9c9efb6c710d138ff132421f7251e0fecbe315baa3bc83bf9bff978e1"

      define_method(:install) do
        bin.install "modu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/qimaotech/modu/releases/download/v0.6.5/modu_0.6.5_darwin_arm64.tar.gz"
      sha256 "7271c07af32a60b7c0a3da96a1560bea2f7a2bf50f6df209fafd330f00acc122"

      define_method(:install) do
        bin.install "modu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/qimaotech/modu/releases/download/v0.6.5/modu_0.6.5_linux_amd64.tar.gz"
      sha256 "0b9e6166bdc0ae464754559707f1d6cab47a3261db445cce036a5b057feb4bfc"
      define_method(:install) do
        bin.install "modu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qimaotech/modu/releases/download/v0.6.5/modu_0.6.5_linux_arm64.tar.gz"
      sha256 "26472cdc582bea65a82df55a6236a395361906a4033f69712f998b6e36a9215a"
      define_method(:install) do
        bin.install "modu"
      end
    end
  end
end
